Repository ManageIQ/manageiq-providers-foreman, pull requests merged in 2019-11, with the labels that each got.

#51 Optionally symlink spec/manageiq during bin/setup
  bin/setup
Labels: enhancement

#52 Add CODEOWNERS
  .github/CODEOWNERS
Labels: documentation

#53 Rely on the default implementation of .ems_class
  app/models/manageiq/providers/foreman/configuration_manager/refresh_worker.rb
  app/models/manageiq/providers/foreman/provisioning_manager/refresh_worker.rb
Labels: refactoring
