Repository ManageIQ/manageiq-providers-foreman, pull requests merged in 2020-09, with the labels that each got.

#69 Fix translation for provider validation message
  app/models/manageiq/providers/foreman/provider.rb
Labels: internationalization

#68 Don't need to override create_from_params
  app/models/manageiq/providers/foreman/configuration_manager.rb
Labels: wip

#71 Make the default credentials required in the provider DDF
  app/models/manageiq/providers/foreman/provider.rb
Labels: bug

#72 Prefer ManageIQ::Password over legacy MiqPassword constant
  app/models/manageiq/providers/foreman/provider.rb
Labels: enhancement
