Repository ManageIQ/manageiq-providers-foreman, pull requests merged in 2020-10, with the labels that each got.

#73 Delegating zone to provider breaks worker_class.where
  app/models/manageiq/providers/foreman/configuration_manager.rb
  app/models/manageiq/providers/foreman/provider.rb
  spec/models/manageiq/providers/foreman/configuration_manager/refresh_worker_spec.rb
Labels: bug

#74 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: test

#64 Switch to manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-providers-foreman.gemspec
Labels: unmergeable

#75 Fix .rubocop_local.yml
  .rubocop_local.yml
Labels: developer
