Repository ManageIQ/manageiq-providers-foreman, pull requests merged in 2020-05, with the labels that each got.

#61 Fix README to point to travis-ci.com instead of travis-ci.org
  README.md
Labels: bug, developer

#63 Removing deprecated Gemnasium badge
  README.md
Labels: developer

#60 Adjusted the DDF schema and validation
  app/models/manageiq/providers/foreman/provider.rb
Labels: enhancement
