Repository ManageIQ/manageiq-providers-foreman, pull requests merged in 2020-03, with the labels that each got.

#55 Add option for graph refresh
  app/models/manageiq/providers/foreman/configuration_manager/refresh_worker.rb
  app/models/manageiq/providers/foreman/configuration_manager/refresher.rb
  app/models/manageiq/providers/foreman/inventory.rb
  app/models/manageiq/providers/foreman/inventory/collector.rb
  app/models/manageiq/providers/foreman/inventory/collector/configuration_manager.rb
  app/models/manageiq/providers/foreman/inventory/collector/foreman.rb
  app/models/manageiq/providers/foreman/inventory/collector/provisioning_manager.rb
  app/models/manageiq/providers/foreman/inventory/parser.rb
  app/models/manageiq/providers/foreman/inventory/parser/configuration_manager.rb
  app/models/manageiq/providers/foreman/inventory/parser/foreman.rb
  app/models/manageiq/providers/foreman/inventory/parser/provisioning_manager.rb
  app/models/manageiq/providers/foreman/inventory/persister.rb
  app/models/manageiq/providers/foreman/inventory/persister/configuration_manager.rb
  app/models/manageiq/providers/foreman/inventory/persister/foreman.rb
  app/models/manageiq/providers/foreman/inventory/persister/provisioning_manager.rb
  app/models/manageiq/providers/foreman/provisioning_manager.rb
  app/models/manageiq/providers/foreman/provisioning_manager/refresh_worker.rb
  app/models/manageiq/providers/foreman/provisioning_manager/refresh_worker/runner.rb
  app/models/manageiq/providers/foreman/provisioning_manager/refresher.rb
  config/settings.yml
  spec/models/manageiq/providers/foreman/configuration_manager/refresher_spec.rb
Labels: enhancement

#56 Foreman provider should allow creation in maintenance zone
  app/models/manageiq/providers/foreman/provider.rb
  spec/models/manageiq/providers/foreman/provider_spec.rb
Labels: bug

#58 remove rest of inventory object refresh
  app/models/manageiq/providers/foreman/configuration_manager.rb
  app/models/manageiq/providers/foreman/provisioning_manager.rb
Labels: cleanup

#59 Delegate endpoints and authentications on managers to the provider
  app/models/manageiq/providers/foreman/configuration_manager.rb
  app/models/manageiq/providers/foreman/provisioning_manager.rb
  spec/models/manageiq/providers/foreman/configuration_manager_spec.rb
Labels: enhancement
