Repository ManageIQ/manageiq-providers-foreman, pull requests merged in 2021-03, with the labels that each got.

#85 Update provider schema with dataType
  app/models/manageiq/providers/foreman/provider.rb
Labels: bug, lasker/yes?

#86 Test with ruby 2.6.6 and 2.7.2 per ManageIQ/manageiq#19678
  .travis.yml
Labels: test

#84 Add systemd unit files for workers
  build/systemd_units/manageiq-providers-foreman_configuration_manager_refresh.target
  build/systemd_units/manageiq-providers-foreman_configuration_manager_refresh@.service
Labels: technical debt
